# Generated by Django 4.2.4 on 2023-09-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_shounen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manhwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('japanese_title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('authors', models.CharField(max_length=100)),
                ('publication_date', models.CharField(max_length=100)),
                ('volume', models.IntegerField(default=0)),
                ('chapter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Manhwa',
                'verbose_name_plural': 'Manhwa',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='seinen',
            options={'ordering': ['title'], 'verbose_name': 'Seinen', 'verbose_name_plural': 'Seinen'},
        ),
        migrations.AlterModelOptions(
            name='shounen',
            options={'ordering': ['title'], 'verbose_name': 'Shounen', 'verbose_name_plural': 'Shounen'},
        ),
        migrations.AlterField(
            model_name='seinen',
            name='chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seinen',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shounen',
            name='chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shounen',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
