# Generated by Django 4.2.4 on 2023-09-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_manhwa_alter_seinen_options_alter_shounen_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('japanese_title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('authors', models.CharField(max_length=100)),
                ('publication_date', models.CharField(max_length=100)),
                ('volume', models.IntegerField(default=0)),
                ('chapter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shoujo',
                'verbose_name_plural': 'Shoujo',
                'ordering': ['title'],
            },
        ),
    ]
