# Generated by Django 4.2.4 on 2023-09-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_shoujo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seinen',
            name='current_estado',
            field=models.CharField(choices=[(1, 'Reading'), (2, 'Plan to Read'), (3, 'Completed')], default=1, max_length=50),
        ),
    ]
