# Generated by Django 4.2.4 on 2023-09-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='title_recommendation',
        ),
    ]
