# Generated by Django 4.2.4 on 2023-09-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_remove_recommendation_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['username'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
