# Generated by Django 4.2.4 on 2023-09-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_rename_recommendation_comment_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manhwa',
            old_name='japanese_title',
            new_name='korean_title',
        ),
        migrations.AddField(
            model_name='manhwa',
            name='current_estado',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Plan to read', 'Plan to read'), ('Completed', 'Completed')], default='Plan to read', max_length=50),
        ),
        migrations.AddField(
            model_name='shoujo',
            name='current_estado',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Plan to read', 'Plan to read'), ('Completed', 'Completed')], default='Plan to read', max_length=50),
        ),
        migrations.AddField(
            model_name='shounen',
            name='current_estado',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Plan to read', 'Plan to read'), ('Completed', 'Completed')], default='Plan to read', max_length=50),
        ),
    ]
