# Generated by Django 4.2.4 on 2023-09-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_alter_addentry_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddEntry',
            new_name='Manga',
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['title'], 'verbose_name': 'Manga', 'verbose_name_plural': 'Manga'},
        ),
    ]
