# Generated by Django 4.2.4 on 2023-09-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_rename_addentry_manga_alter_manga_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'Manga', 'verbose_name_plural': 'Manga'},
        ),
    ]
