# Generated by Django 4.2.4 on 2023-09-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_alter_manga_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['-title'], 'verbose_name': 'Manga', 'verbose_name_plural': 'Manga'},
        ),
    ]
