# Generated by Django 4.2.4 on 2023-09-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0021_review_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(0, 'Not Yet Scored'), (1, '1 Apalling'), (2, '2 Horrible'), (3, '3 Very Bad'), (4, '4 Bad'), (5, '5 Avarage'), (6, '6 Fine'), (7, '7 Good'), (8, '8 Very Good'), (9, '9 Great'), (10, '10 Masterpiece')], default=0, max_length=50),
        ),
    ]
