# Generated by Django 4.2.4 on 2023-09-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0024_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('Not Yet Scored', 'Not Yet Scored'), ('1', '1 (Apalling)'), ('3', '2 (Horrible)'), ('3', '3 (Very Bad)'), ('4', '4 (Bad)'), ('5', '5 (Avarage)'), ('6', '6 (Fine)'), ('7', '7 (Good)'), ('8', '8 (Very Good)'), ('9', '9 (Great)'), ('10', '10 (Masterpiece)')], default='Not Yet Scored', max_length=50),
        ),
    ]
